### PR TITLE
add logging and do not fail on HAPP2HOST update error

### PR DESCRIPTION
**Pull request by peeech**

### CODE REVIEW

**Comment by peeech** [comment]
Now the question is how do I pass `environment.RUST_LOG = "debug";` to this script and what will collect the logging output. I assume `journal.log` but is that true?

**Comment by Br1ght0ne** [comment]
@peeech `systemd.services.<name>.environment` is the place to put `RUST_LOG`. And yes, `journalctl` takes care of putting service's stderr into logs.

**Review by Br1ght0ne — COMMENTED** [review]
Maybe switch `error!` to `warn!`, as `error!` is for actual mission-critical stuff?

**Comment by peeech** [comment]
> @peeech `systemd.services.<name>.environment` is the place to put `RUST_LOG`. And yes, `journalctl` takes care of putting service's stderr into logs.

The thing is that adding `environment.RUST_LOG = "debug";` to `systemd.services.holochain-conductor = ...` is not working. I checked `journalctl` and there's no sign of logging. It seems that script called in `preStart` is not affected.

**Comment by peeech** [comment]
> Maybe switch `error!` to `warn!`, as `error!` is for actual mission-critical stuff?

Good idea, switched to warn!

**Comment by peeech** [comment]
> @peeech `systemd.services.<name>.environment` is the place to put `RUST_LOG`. And yes, `journalctl` takes care of putting service's stderr into logs.

I ended up per your suggestion setting logging level to info in the code itself

**Pull request merged**
